import 'package:hospitalmonitor/business_logic/models/analysis_model.dart';

List<AnalysisModel> analysises = [
  AnalysisModel(
    analysisID: '0',
    analystID: '0',
    analystName: 'analyst',
    patientID: '1',
    patientName: 'patient1',
    date: '25/6/2006',
    labName: 'Almotehda lab',
    analysisUrl: 'mafesh URl',
    notes: 'gooood',
  ),
  AnalysisModel(
    analysisID: '10',
    analystID: '0',
    analystName: 'analyst',
    patientID: '2',
    patientName: 'patient2',
    date: '25/2/1995',
    labName: 'Almotehda lab',
    analysisUrl: 'https://english.ahram.org.eg/Portal/9/Heritage.aspx',
    notes: 'BAAAAAAAAAAAAAAAAAAAAAAAD',
  ),
  AnalysisModel(
    analysisID: '20',
    analystID: '2',
    analystName: 'analyst2',
    patientID: '0',
    patientName: 'patient',
    date: '25/2/2008',
    labName: 'Almotehda lab',
    analysisUrl: 'https://english.ahram.org.eg/Portal/7/Life--Style.aspx',
    notes: '',
  ),
  AnalysisModel(
    analysisID: '30',
    analystID: '2',
    analystName: 'analyst2',
    patientID: '1',
    patientName: 'patient1',
    date: '30/8/2006',
    labName: 'Almotehda lab',
    analysisUrl: 'mafesh URl',
    notes: 'gooood',
  ),
  AnalysisModel(
    analysisID: '40',
    analystID: '1',
    analystName: 'analyst1',
    patientID: '0',
    patientName: 'patient',
    date: '25/12/2006',
    labName: 'Almotehda lab',
    analysisUrl: 'https://english.ahram.org.eg/Portal/2/World.aspx',
    notes: 'SO  gooood',
  ),
  AnalysisModel(
    analysisID: '50',
    analystID: '2',
    analystName: 'analyst2',
    patientID: '1',
    patientName: 'patient1',
    date: '25/6/2096',
    labName: 'Almotehda lab',
    analysisUrl: 'https://english.ahram.org.eg/Portal/3/Business.aspx',
    notes: 'go',
  ),
  AnalysisModel(
    analysisID: '90',
    analystID: '2',
    analystName: 'analyst2',
    patientID: '2',
    patientName: 'patient2',
    date: '27/6/2006',
    labName: 'Almotehda lab',
    analysisUrl:
        'https://english.ahram.org.eg/NewsContent/1/64/410431/Egypt/Politics-/Egypt-steps-up-readiness-at-hospitals-ahead-of-Sha.aspx',
    notes: 'goo000ood',
  ),
  AnalysisModel(
    analysisID: '100',
    analystID: '1',
    analystName: 'analyst1',
    patientID: '2',
    patientName: 'patient2',
    date: '25/7/2006',
    labName: 'Almotehda lab',
    analysisUrl: 'https://english.ahram.org.eg/',
    notes: 'baD',
  ),
];
