import 'package:hospitalmonitor/business_logic/models/examination_model.dart';

List<ExaminationModel> examinations = [
  ExaminationModel(
    examinationID: '10',
    doctorID: '0',
    doctorName: 'Ahmed',
    patientID: '0',
    patientName: 'Samy',
    date: '1/1/2001',
    symptoms: 'nothing',
    description: 'nothing',
    disease: "corona",
    drugs: ["betadine 3 times day", "Aspirin 2 times per day"],
  ),
  ExaminationModel(
    examinationID: '20',
    doctorID: '1',
    doctorName: 'Ahmed1',
    patientID: '0',
    patientName: 'Samy',
    date: '1/1/2001',
    symptoms: 'nothing',
    description: 'nothing',
    disease: "corona",
    drugs: ["betadine 3 times day", "Aspirin 2 times per day"],
  ),
  ExaminationModel(
    examinationID: '30',
    doctorID: '2',
    doctorName: 'Ahmed2',
    patientID: '1',
    patientName: 'Yehia',
    date: '1/1/2005',
    symptoms: 'bone break',
    description: '3yan',
    disease: "corona",
    drugs: ["betadine 3 times day", "Aspirin 2 times per day"],
  ),
  ExaminationModel(
    examinationID: '40',
    doctorID: '2',
    doctorName: 'Ahmed2',
    patientID: '2',
    patientName: 'Samy2',
    date: '1/1/2008',
    symptoms: 'stomach ache',
    description: 'may be she is pregnant!',
    disease: "corona",
    drugs: ["betadine 3 times day", "Aspirin 2 times per day"],
  ),
  ExaminationModel(
    examinationID: '50',
    doctorID: '1',
    doctorName: 'Ahmed1',
    patientID: '0',
    patientName: 'Samy',
    date: '1/1/2002',
    symptoms: 'teeth pain',
    description: 'bad teeth',
    disease: "corona",
    drugs: ["betadine 3 times day", "Aspirin 2 times per day"],
  ),
  ExaminationModel(
    examinationID: '60',
    doctorID: '0',
    doctorName: 'Ahmed',
    patientID: '1',
    patientName: 'Yehia',
    date: '1/1/2025',
    symptoms: 'nothing',
    description: 'nothing',
    disease: "corona",
    drugs: ["betadine 3 times day", "Aspirin 2 times per day"],
  ),
  ExaminationModel(
    examinationID: '70',
    doctorID: '1',
    doctorName: 'Ahmed1',
    patientID: '0',
    patientName: 'Samy',
    date: '1/1/2001',
    symptoms: 'nothing',
    description: 'nothing',
    disease: "corona",
    drugs: ["betadine 3 times day", "Aspirin 2 times per day"],
  ),
  ExaminationModel(
    examinationID: '80',
    doctorID: '2',
    doctorName: 'Ahmed2',
    patientID: '2',
    patientName: 'Samy2',
    date: '1/1/2001',
    symptoms: 'nothing',
    description: 'nothing',
    disease: "corona",
    drugs: ["betadine 3 times day", "Aspirin 2 times per day"],
  ),
  ExaminationModel(
    examinationID: '900',
    doctorID: '0',
    doctorName: 'Ahmed',
    patientID: '2',
    patientName: 'Samy2',
    date: '1/1/2012',
    symptoms: 'nothing',
    description: 'nothing',
    disease: "corona",
    drugs: ["betadine 3 times day", "Aspirin 2 times per day"],
  ),
];
