import 'package:hospitalmonitor/business_logic/models/examination_model.dart';

List<ExaminationModel> examinations = [
  ExaminationModel(
    examinationID: '10',
    doctorID: '0',
    doctorName: 'doctor',
    patientID: '0',
    patientName: 'Samy',
    date: '1/1/2001',
    symptoms: 'nothing',
    examinationResult: 'nothing',
    notes: 'playful child',
  ),
  ExaminationModel(
    examinationID: '20',
    doctorID: '1',
    doctorName: 'doctor1',
    patientID: '0',
    patientName: 'Samy',
    date: '1/1/2001',
    symptoms: 'nothing',
    examinationResult: 'nothing',
    notes: 'playful child',
  ),
  ExaminationModel(
    examinationID: '30',
    doctorID: '2',
    doctorName: 'doctor2',
    patientID: '1',
    patientName: 'Samy1',
    date: '1/1/2005',
    symptoms: '????',
    examinationResult: '3yan',
    notes: 'should visit a doctor!',
  ),
  ExaminationModel(
    examinationID: '40',
    doctorID: '2',
    doctorName: 'doctor2',
    patientID: '2',
    patientName: 'Samy2',
    date: '1/1/2008',
    symptoms: 'stomach ache',
    examinationResult: 'may be she is pregnant!',
    notes: 'should got to the hospital!',
  ),
  ExaminationModel(
    examinationID: '50',
    doctorID: '1',
    doctorName: 'doctor1',
    patientID: '0',
    patientName: 'Samy',
    date: '1/1/2002',
    symptoms: 'teeth pain',
    examinationResult: 'bad teeth',
    notes: 'remove his teeth',
  ),
  ExaminationModel(
    examinationID: '60',
    doctorID: '0',
    doctorName: 'doctor',
    patientID: '1',
    patientName: 'Samy1',
    date: '1/1/2025',
    symptoms: 'nothing',
    examinationResult: 'nothing',
    notes: '',
  ),
  ExaminationModel(
    examinationID: '70',
    doctorID: '1',
    doctorName: 'doctor1',
    patientID: '0',
    patientName: 'Samy',
    date: '1/1/2001',
    symptoms: 'nothing',
    examinationResult: 'nothing',
    notes: 'playful child',
  ),
  ExaminationModel(
    examinationID: '80',
    doctorID: '2',
    doctorName: 'doctor2',
    patientID: '2',
    patientName: 'Samy2',
    date: '1/1/2001',
    symptoms: 'nothing',
    examinationResult: 'nothing',
    notes: 'good girl',
  ),
  ExaminationModel(
    examinationID: '900',
    doctorID: '1',
    doctorName: 'doctor',
    patientID: '2',
    patientName: 'Samy2',
    date: '1/1/2012',
    symptoms: 'nothing',
    examinationResult: 'nothing',
    notes: 'good boy',
  ),
];
