import 'package:hospitalmonitor/business_logic/models/radio_model.dart';

List<RadioModel> radios = [
  RadioModel(
    radioID: '0',
    radiologistID: '0',
    radioName: 'Brain',
    patientID: '0',
    patientName: 'Samy',
    date: '1/5/2880',
    radiologistName: 'Ashraf',
    radioUrl: 'https://akhbarelyom.com/',
    notes: '',
  ),
  RadioModel(
    radioID: '10',
    radiologistID: '1',
    radioName: 'head',
    patientID: '0',
    patientName: 'Samy',
    date: '1/5/280',
    radiologistName: 'Ashraf1',
    radioUrl:
        'https://akhbarelyom.com/news/newssection/170/1/%D8%AD%D9%83%D8%A7%D9%8A%D8%A7%D8%AA',
    notes: '',
  ),
  RadioModel(
    radioID: '20',
    radiologistID: '1',
    radioName: 'blood',
    patientID: '2',
    patientName: 'Samy2',
    date: '1/5/2880',
    radiologistName: 'Ashraf1',
    radioUrl:
        'https://akhbarelyom.com/news/newssection/10/1/%D8%A7%D9%82%D8%AA%D8%B5%D8%A7%D8%AF',
    notes: '',
  ),
  RadioModel(
    radioID: '30',
    radiologistID: '1',
    radioName: 'kidney',
    patientID: '1',
    patientName: 'patient1',
    date: '1/5/2003',
    radiologistName: 'Ashraf1',
    radioUrl:
        'https://akhbarelyom.com/news/newssection/160/1/%D8%AD%D9%88%D8%A7%D8%B1%D8%A7%D8%AA-%D9%88%D8%AA%D8%AD%D9%82%D9%8A%D9%82%D8%A7%D8%AA',
    notes: '',
  ),
  RadioModel(
    radioID: '40',
    radiologistID: '2',
    radioName: 'bone',
    patientID: '2',
    patientName: 'Samy2',
    date: '1/5/2880',
    radiologistName: 'Ashraf2',
    radioUrl: 'https://akhbarelyom.com/',
    notes: '',
  ),
  RadioModel(
    radioID: '50',
    radiologistID: '0',
    radioName: 'bone',
    patientID: '1',
    patientName: 'Yehia',
    date: '1/5/2880',
    radiologistName: 'Ashraf2',
    radioUrl: 'https://akhbarelyom.com/',
    notes: '',
  ),
  RadioModel(
    radioID: '60',
    radiologistID: '2',
    radioName: 'skull',
    patientID: '1',
    patientName: 'Samy1',
    date: '1/5/2880',
    radiologistName: 'Ashraf2',
    radioUrl: 'https://akhbarelyom.com/',
    notes: '',
  ),
];
